version: "3.8"

services:
  backend:
    build: 
      context: ./backend
    container_name: dukan-backend
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build: 
      context: ./dukan-frontend
    container_name: dukan-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped
